Kruchinin -- Homework #1
KruchDmitriy/java-2-au-course pull request #1
Opened 2017-09-20 22:52 UTC by KruchDmitriy

2017-09-25 16:07 UTC, KruchDmitriy commented
@dsavvinov

2017-10-03 17:51 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +    private Thread[] workers;
`final`?

2017-10-03 18:05 UTC, dsavvinov requested changes
Отправлено на доработку

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +    public int getNumThreads() {
Раз уж создал интерфейс, то логично было бы этот метод туда поместить.

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +    private Thread[] workers;
`final`?

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +            while (tasksQueue.size() == 0) {
`tasksQueue.isEmpty()`

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +        private LightFutureImpl<T> lightFuture = new LightFutureImpl<>();
Почему не `final`? В многопоточном окружении отсутствие `final` может привести к [интересным и неожиданным эффектам](https://shipilev.net/blog/2016/close-encounters-of-jmm-kind/#wishful-tso-is-fine). 
Когда пройдете JMM, предлагаю, если интересно, вернуться к этому коду и обсудить, корректно ли он синхронизован без `final`.

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +        private boolean isReady = false;
Minor: избыточный инициализатор

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +        private boolean wasThrown = false;
Minor: избыточный инициализатор

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +                    return function.apply(get());
Если воркер возьмет такую таску (а какой-нибудь из них рано или поздно возьмет её), то если зависимая таска еще не завершена, он *заблокируется до ее завершения*. Это означает, что у тебя в пуле начнет простаивать один тред, что недопустимо.
Это обязательно нужно исправить.

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +            notify();
Что, если несколько потоков сделали `get()` на этой `LightFuture`?

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +            notify();
Аналогичный вопрос

2017-10-03 18:05 UTC, dsavvinov commented on src/test/java/ru/spbau/mit/ThreadPoolImplTest.java
> +    public void testTaskConsistency() throws LightExecutionException, InterruptedException {
Что этот тест тестирует?

2017-10-03 18:05 UTC, dsavvinov commented on src/test/java/ru/spbau/mit/ThreadPoolImplTest.java
> +    public void testQueueConsistency() throws LightExecutionException, InterruptedException {
Что этот тест проверяет?

2017-10-03 18:05 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPool.java
> +public interface ThreadPool {
Minor: если очень хотелось от чего-то отнаследоваться (это вполне разумное и хорошее желание), то лучше взять `ExecutorSerivce`. 
У него чуть более широкий интерфейс, чем у нашего пула, поэтому не настаиваю на этой правке.

2017-10-03 18:30 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +                lightFuture.setWasThrown();
Мне, как пользователю такого пула, нужно знать не только факт того, что моя таска упала, но еще и с каким эксепшеном (это можно делать, если прикрепить реальный эксепшен в `cause` у `LightFutureException`).

2017-10-09 11:32 UTC, KruchDmitriy commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +            notify();
Поправил, написал тест.

2017-10-09 11:33 UTC, KruchDmitriy commented on src/main/java/ru/spbau/mit/ThreadPool.java
> +public interface ThreadPool {
Отнаследоваться хотел, но не смог, из-за внутренних противоречий :smiley:, запрещено использовать concurrent, а интерфейсы в executorService принимают, например, Callable, поэтому без его использования переписать не получиться.

2017-10-09 11:34 UTC, KruchDmitriy commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +                    return function.apply(get());
Поправил, но привело к добавлению synchronized в цикл worker'а. По-другому как сделать пока не придумал(.

2017-10-09 11:35 UTC, KruchDmitriy commented
Исправил замечания + добавил тесты + пофиксил метод shutdown.
@dsavvinov

2017-10-18 09:01 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +        PackagedTask getNextTask() {
`synchronized`? Тогда не придется в `Worker.run` делать синхронизацию на локальном инстансе.

2017-10-18 09:04 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +            nextTask = new PackagedTask<>(supplier);
Если на одном и том же `LightFutureImpl` много раз позвать `thenApply` с разными тасками, то должны получить эдакий "веер". Исполнятся это должно следующим образом: сначала исполняется исходная задача, и потом в пул сабмитятся *все* зависимые и начинают исполнятся на общих началах с остальными.

В данном случае, поле `nextTask` будет перетёрто, и автоматически исполнится только последняя задача, которая была передана в `thenApply`, а остальные *не будут исполнятся до тех пор, пока на них явно не будет вызван `get`*

2017-10-18 09:11 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +            PackagedTask task = null;
Здесь и далее: raw types крайне не рекомендованы к использованию. В данном случае нет никакой мотивации их использовать, и от них можно легко избавиться аккуратной расстановкой wildcard'ов.

2017-10-18 09:18 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/ThreadPoolImpl.java
> +        private boolean isReady;
Кажется, есть ошибка синхронизации на `isReady`.
Сделаем так. Я снимаю 0.5 баллов за это "в долг". Как только сможешь объяснить, что здесь за ошибка, как она проявляется и почему с точки зрения Java Memory Model такое поведение действительно может проявиться (ну или доказать, что все на самом деле работает правильно) -- верну баллы обратно :)

2017-10-18 09:22 UTC, dsavvinov commented
По сравнению с первой версией намного лучше, но косяк с `thenApply` серьезный, -1.5 балла за него, еще -0.5 за всякие мелочи и 0.5 -- долг по JMM.

Итого пока 7.5 баллов, максимум 8.0 баллов.

2017-10-19 07:12 UTC, merged